name: answer_book
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip=21.2.4
  - pip:
    - flask==2.3.3
    - flask-cors==4.0.0
    - python-dotenv==1.0.0
    - Werkzeug==2.3.7
    - Jinja2==3.1.2
    - MarkupSafe==2.1.3
    - itsdangerous==2.1.2
    - click==8.1.7
    - pytz==2023.3